name: Build & Deploy to DEV via ArgoCD

on:
  push:
    branches:
      - dev
      - uat

env:
  ACR_REPOSITORY: common-pk-service
  VALUES_FILE: yap/services/common-pk-service/values-dev.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: maven:3.9.9-eclipse-temurin-21
      options: --user root

    env:
      NEXUS_USER: ${{ secrets.NEXUS_USER }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

    steps:
      - name: Install Node.js
        run: |
          apt-get update
          apt-get install -y curl gnupg
          curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs

      - uses: actions/checkout@v4

      - name: Configure Maven settings.xml
        run: |
          mkdir -p /root/.m2
          sed -e "s|\${NEXUS_USER}|$NEXUS_USER|g" \
              -e "s|\${NEXUS_PASSWORD}|$NEXUS_PASSWORD|g" \
              settings.xml > /root/.m2/settings.xml

      - name: Build JAR
        run: mvn clean package -s /root/.m2/settings.xml -DskipTests

      - name: Install Docker CLI
        run: |
          apt-get update
          apt-get install -y docker.io

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | bash

      - name: Login ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login \
            ${{ secrets.ACR_LOGIN_SERVER }} \
            -u ${{ secrets.ACR_USERNAME }} \
            --password-stdin

      - name: Set IMAGE TAG
        run: |
          BRANCH_NAME=$(echo "$GITHUB_REF_NAME" | tr '/' '-')
          IMAGE_TAG="${BRANCH_NAME}-${GITHUB_RUN_NUMBER}"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "Using IMAGE_TAG=$IMAGE_TAG"

      - name: Build Image
        run: |
          docker build \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/$ACR_REPOSITORY:$IMAGE_TAG .

      - name: Push Image
        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/$ACR_REPOSITORY:$IMAGE_TAG

      - name: Update GitOps Repo
        if: github.ref_name != 'uat'
        run: |
          git config --global user.email "sambath.r@datasirpi.com"
          git config --global user.name "sam-r17"

          git clone https://x-access-token:${{ secrets.GIT_TOKEN }}@gitea.yap.com/yapdigital/yap-helm.git
          cd yap-helm

          echo "Updating ${VALUES_FILE} → tag: ${IMAGE_TAG}"
          sed -i "s/tag: .*/tag: ${IMAGE_TAG}/" ${VALUES_FILE}

          git add ${VALUES_FILE}
          git commit -m "Deploy common-pk-service ${IMAGE_TAG} to DEV via CI"
          git push origin main
 
